
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MANsys
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerOldBooking
{

    public int Id { get; set; }

    public string CustomerMail { get; set; }

    public string CustomerName { get; set; }

    public string CustomerPhoneNumber { get; set; }

    public string BookingDate { get; set; }

    public string BookingMessage { get; set; }

    public string RestaurantMail { get; set; }

}

}
