

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MANsys
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GlobalDesignEntities : DbContext
{
    public GlobalDesignEntities()
        : base("name=GlobalDesignEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CustomerAccount> CustomerAccount { get; set; }

    public virtual DbSet<CustomerService> CustomerService { get; set; }

    public virtual DbSet<RestaurantAccounts> RestaurantAccounts { get; set; }

    public virtual DbSet<RestaurantCategories> RestaurantCategories { get; set; }

    public virtual DbSet<RestaurantItems> RestaurantItems { get; set; }

    public virtual DbSet<RestaurantProcess> RestaurantProcess { get; set; }

    public virtual DbSet<RestaurantTable> RestaurantTable { get; set; }

    public virtual DbSet<CustomerOldBooking> CustomerOldBooking { get; set; }

    public virtual DbSet<TableIncome> TableIncome { get; set; }

}

}

