
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MANsys
{

using System;
    using System.Collections.Generic;
    
public partial class RestaurantAccounts
{

    public int Id { get; set; }

    public string RestaurantName { get; set; }

    public string RestaurantMail { get; set; }

    public string RestaurantPassword { get; set; }

    public string ConfirmPassword { get; set; }

    public string RestaurantAdress { get; set; }

    public string RestaurantDistrict { get; set; }

    public string RestaurantCity { get; set; }

    public string RestaurantPhone { get; set; }

}

}
